
Workarea::Configuration.define_fields do
  fieldset 'Gift Cards', namespaced: false do
    field 'Gift Card Token Length',
      type: :integer,
      default: 8,
      description: 'Length of digital gift card numbers generated by Workarea.'

    field 'Max Gift Cards Per Order',
      type: :integer,
      default: 10,
      description: 'How many gift cards can be applied to a single order.'
  end
end
